server:
  port: 8085
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet.context-path: /api/v1

#upload.static.local: /static

web.upload-path: E:/upload/

file:
  upload-dir: ./uploads

spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

  mvc:
    static-path-pattern: /**
  resources:
    static-locations:
      classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,ResourceEntity:${web.upload-path}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1000MB
      max-request-size: 1000MB


  datasource:
    name: Resource
#    数据库连接地址
    url: jdbc:mysql://39.96.221.167:3306/Resource?useUnicode=true&characterEncoding=utf8
#    数据库用户名
    username: root
#    数据库连接密码
    password: yx20

#   配置mysql驱动
    driverClassName: com.mysql.jdbc.Driver
#   配置当前要使用的数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
        # 进行数据库连接池的配置
      min-idle: 5
        # 数据库连接池的最小维持连接数
      initial-size: 5
        # 初始化提供的连接数
      max-total: 5
        # 最大的连接数
      max-wait-millis: 200
        # 等待连接获取的最大超时时间

#    mybatis的mapper配置文件
mybatis:
  config-location: classpath:mybatis-config.xml  # mybatis配置文件所在路径
  mapper-locations: classpath:mapper/*.xml   # 所有的mapper映射文件
  type-aliases-package: com.syx.management.core.mapper # 定义所有操作类的别名所在包
debug: true
# JWT配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenprefix: JWT-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 超时时间   单位秒
  access_token: 3600
  # 刷新token时间   单位秒
  refresh_token: 3600
  # 配置不需要认证的接口
  antMatchers: /api/v1/user/login,
#  route:
#    authentication:
#      path: /index/**/login/**,/favicon.ico

# Mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl









    


